let testImageOne = document.getElementById("photo-one")
let testImageTwo = document.getElementById("photo-two")
let testImageThree = document.getElementById("photo-three")
let testImageFour = document.getElementById("photo-four")
let testImageFive = document.getElementById("photo-five")
let testImageSix = document.getElementById("photo-six")
let testImageSeven = document.getElementById("photo-seven")
let testImageEight = document.getElementById("photo-eight")
let testImageNine = document.getElementById("photo-nine")
let testImageTen = document.getElementById("photo-ten")
let testImageEleven = document.getElementById("photo-eleven")
let testImageTwelve = document.getElementById("photo-twelve")
let testImageThirteen = document.getElementById("photo-thirteen")
let testImageFourteen = document.getElementById("photo-fourteen")
let testImageFifteen = document.getElementById("photo-fifteen")
let testImageSixteen = document.getElementById("photo-sixteen")
let testImageSeventeen = document.getElementById("photo-seventeen")
let testImageEighteen = document.getElementById("photo-eighteen")
let testImageNineteen = document.getElementById("photo-nineteen")
let testImageTwenty = document.getElementById("photo-twenty")
let testImageTwentyOne = document.getElementById("photo-twenty-one")
let testImageTwentyTwo = document.getElementById("photo-twenty-two")
let testImageTwentyThree = document.getElementById("photo-twenty-three")

let one = Math.floor(Math.random() * 22) + 1
let two = Math.floor(Math.random() * 22) + 1
let three = Math.floor(Math.random() * 22) + 1
let four = Math.floor(Math.random() * 22) + 1
let five = Math.floor(Math.random() * 22) + 1
let six = Math.floor(Math.random() * 22) + 1
let seven = Math.floor(Math.random() * 22) + 1
let eight = Math.floor(Math.random() * 22) + 1
let nine = Math.floor(Math.random() * 22) + 1
let ten = Math.floor(Math.random() * 22) + 1
let eleven = Math.floor(Math.random() * 22) + 1
let twelve = Math.floor(Math.random() * 22) + 1
let thirteen = Math.floor(Math.random() * 22) + 1
let fourteen = Math.floor(Math.random() * 22) + 1
let fifteen = Math.floor(Math.random() * 22) + 1
let sixteen = Math.floor(Math.random() * 22) + 1
let seventeen = Math.floor(Math.random() * 22) + 1
let eighteen = Math.floor(Math.random() * 22) + 1
let nineteen = Math.floor(Math.random() * 22) + 1
let twenty = Math.floor(Math.random() * 22) + 1
let twentyOne = Math.floor(Math.random() * 22) + 1
let twentyTwo = Math.floor(Math.random() * 22) + 1
let twentyThree = Math.floor(Math.random() * 22) + 1




testImageOne.src = one + ".jpg"
testImageTwo.src = two + ".jpg"
testImageThree.src = three + ".jpg"
testImageFour.src = four + ".jpg"
testImageFive.src = five + ".jpg"
testImageSix.src = six + ".jpg"
testImageSeven.src = seven + ".jpg"
testImageEight.src = eight + ".jpg"
testImageNine.src = nine + ".jpg"
testImageTen.src = ten + ".jpg"
testImageEleven.src = eleven + ".jpg"
testImageTwelve.src = twelve + ".jpg"
testImageThirteen.src = thirteen + ".jpg"
testImageFourteen.src = fourteen + ".jpg"
testImageFifteen.src = fifteen + ".jpg"
testImageSixteen.src = sixteen + ".jpg"
testImageSeventeen.src = seventeen + ".jpg"
testImageEighteen.src = eighteen + ".jpg"
testImageNineteen.src = nineteen + ".jpg"
testImageTwenty.src = twenty + ".jpg"
testImageTwentyOne.src = twentyOne + ".jpg"
testImageTwentyTwo.src = twentyTwo + ".jpg"
testImageTwentyThree.src = twentyThree + ".jpg"